export type Project = {
  id: string
  title: string
  shortDescription: string
  fullDescription: string
  context: string
  role: string
  architecture: string
  results: string
  nextSteps: string
  tags: string[]
  featured: boolean
  liveUrl?: string
  githubUrl?: string
  demoUrl?: string
}

export const projects: Project[] = [
  {
    id: "highlevel-courses",
    title: "HighLevel: Courses Platform",
    shortDescription: "Real‑time WYSIWYG Course Builder with responsive previews, multilingual support, and mobile parity via Capacitor.",
    fullDescription: "Creator‑led all‑in‑one course and community builder. Needed fast authoring, responsive previews, and growth features.",
    context: "Large feature surface; multiple teams; accessibility and mobile parity requirements.",
    role: "Led frontend architecture; built WYSIWYG Course Builder; drove UX modernization; added multilingual, commenting, and themes.",
    architecture: "React/TypeScript, Next.js, Module Federation, caching, responsive emulation; Firebase/GCP backend.",
    results: "Higher authoring speed, better accessibility and engagement. Improved time-to-publish for course creators.",
    nextSteps: "Add structured performance budgets and automated a11y tests in CI.",
    tags: ["React", "TypeScript", "Module Federation", "Capacitor", "Firebase", "Next.js"],
    featured: true,
  },
  {
    id: "credentials-platform",
    title: "HighLevel: Credentials/Badge Platform",
    shortDescription: "Canva/Certifier‑style credential creator with verification, bulk issuance, and analytics.",
    fullDescription: "Canvas‑style credential creator with CSV bulk issuance, verification system, and analytics dashboard.",
    context: "Brand customization, secure verification, automation across internal apps.",
    role: "Built Canvas‑based editor, CSV issuance, revocation/renewals, and recipient portal; added analytics and issuer verification.",
    architecture: "React/TypeScript, Canvas APIs, UUID‑based verification, API integrations; micro‑frontends.",
    results: "Faster credential turnaround; improved share/verification rates. Automated bulk issuance for large organizations.",
    nextSteps: "Public API + webhooks; signed PDFs and L2 verifications.",
    tags: ["React", "TypeScript", "Canvas APIs", "Micro-frontends", "Analytics"],
    featured: true,
  },
  {
    id: "dmrv-platform",
    title: "DMRV Web App",
    shortDescription: "Digital Measurement, Reporting, Verification for environmental data with real‑time updates.",
    fullDescription: "Digital Measurement, Reporting, Verification for environmental data. Modular, real‑time, secure.",
    context: "Large datasets; interoperability with external systems; access control.",
    role: "End‑to‑end ownership: architecture, component library, real‑time APIs, SSR, and caching strategies.",
    architecture: "React, Next.js, TypeScript, Shadcn UI, SSR, lazy loading, caching.",
    results: "High‑performance UI, secure flows, and up‑to‑date reporting. Reduced data processing time significantly.",
    nextSteps: "Data lineage views, audit exports, and anomaly detection.",
    tags: ["React", "Next.js", "TypeScript", "Shadcn UI", "SSR"],
    featured: true,
  },
  {
    id: "renew-climate",
    title: "ReNew Power Climate‑Tech Platform",
    shortDescription: "Real‑time energy/climate data with secure multi‑role access and SSR.",
    fullDescription: "Enterprise-grade climate and energy monitoring platform with real-time data synchronization.",
    context: "Heavy datasets; SEO requirements; reliability and security needs.",
    role: "Implemented Next.js SSR, TypeScript+Zod contracts, Firebase realtime APIs; optimized data flow and storage.",
    architecture: "React, Next.js, TypeScript, Firebase, Redux, Node, GCP.",
    results: "Faster loads, reliable real‑time sync, fewer auth issues. Improved data accuracy and reporting speed.",
    nextSteps: "Partitioned data caches, stream processing, and back‑pressure controls.",
    tags: ["React", "Next.js", "TypeScript", "Firebase", "GCP", "Redux"],
    featured: false,
  },
  {
    id: "carbon-shop",
    title: "Carbon Shop",
    shortDescription: "Carbon credit trading platform with RBAC, real‑time sync, and interactive dashboards.",
    fullDescription: "Carbon credit trading marketplace with role-based access control and real-time market updates.",
    context: "Trading platform requiring secure transactions and real-time market data.",
    role: "Full-stack development with focus on real-time features and secure transactions.",
    architecture: "Angular, Firebase, Real-time Database, Cloud Functions.",
    results: "Functional trading platform with secure transaction handling and real-time updates.",
    nextSteps: "Enhanced analytics, automated trading features, and market insights.",
    tags: ["Angular", "Firebase", "Real-time", "Trading"],
    featured: false,
    liveUrl: "[ADD LINK]",
    githubUrl: "[ADD LINK]",
  },
  {
    id: "khajuraho-expo",
    title: "Khajuraho Expo",
    shortDescription: "Mobile‑first web tour with multi‑language audio guides, QR navigation, and 360° map.",
    fullDescription: "Interactive tourism application with immersive audio guides and location-based navigation.",
    context: "Tourism application requiring offline capabilities and multi-language support.",
    role: "Frontend development with focus on PWA capabilities and interactive maps.",
    architecture: "React, PWA, Web Audio API, Geolocation API, Service Workers.",
    results: "Engaging tourist experience with offline support and multiple language options.",
    nextSteps: "AR features and enhanced 360° virtual tours.",
    tags: ["React", "PWA", "Audio", "Maps", "Tourism"],
    featured: false,
    liveUrl: "[ADD LINK]",
  },
  {
    id: "afis-schoolbus",
    title: "AFIS Schoolbus Tracking",
    shortDescription: "Cross‑platform mobile app with GPS live tracking, alerts, and multi‑tenant ops.",
    fullDescription: "School transportation management system with real-time tracking and parental notifications.",
    context: "Safety-critical application requiring reliable GPS tracking and instant notifications.",
    role: "Cross-platform mobile development with real-time location tracking.",
    architecture: "React Native, Firebase, Google Maps API, Push Notifications.",
    results: "Improved student safety and parental peace of mind with real-time tracking.",
    nextSteps: "Route optimization and predictive arrival times.",
    tags: ["React Native", "Firebase", "GPS", "Mobile"],
    featured: false,
    liveUrl: "[ADD LINK]",
    githubUrl: "[ADD LINK]",
  },
  {
    id: "innovative-service-center",
    title: "Innovative Service Center",
    shortDescription: "End‑to‑end SaaS for service centers: bookings, dashboards, invoices, reminders.",
    fullDescription: "Complete service center management system with booking, invoicing, and customer management.",
    context: "Service business requiring comprehensive management and automation.",
    role: "Full-stack SaaS development from concept to deployment.",
    architecture: "MERN Stack, Node.js, Express, MongoDB, React.",
    results: "Streamlined service operations and improved customer satisfaction.",
    nextSteps: "Mobile app and advanced analytics.",
    tags: ["MERN", "SaaS", "Node.js", "MongoDB"],
    featured: false,
    demoUrl: "[ADD LINK]",
  },
  {
    id: "hyre-me",
    title: "Hyre Me",
    shortDescription: "Local job platform with WebSocket notifications, admin dashboards, and geo‑tagged listings.",
    fullDescription: "Local job marketplace connecting employers with job seekers in their area.",
    context: "Job platform requiring real-time communication and location-based matching.",
    role: "Full-stack development with emphasis on real-time features.",
    architecture: "MEAN Stack, WebSocket, MongoDB, Angular.",
    results: "Active local job marketplace with real-time job alerts.",
    nextSteps: "AI-powered job matching and enhanced recommendation engine.",
    tags: ["MEAN", "WebSocket", "MongoDB", "Angular"],
    featured: false,
    liveUrl: "[ADD LINK]",
  },
  {
    id: "haspr-portfolio",
    title: "Haspr Portfolio",
    shortDescription: "Interactive GSAP/Three.js personal site with performant animations.",
    fullDescription: "Creative portfolio website with advanced animations and 3D elements.",
    context: "Portfolio site requiring unique visual experience while maintaining performance.",
    role: "Frontend development with focus on animations and performance.",
    architecture: "React, GSAP, Three.js, WebGL.",
    results: "Engaging visual experience with smooth 60fps animations.",
    nextSteps: "Enhanced 3D interactions and WebGL shaders.",
    tags: ["React", "GSAP", "Three.js", "WebGL"],
    featured: false,
    liveUrl: "[ADD LINK]",
  },
]
